const actionTypes = {
    LOGINLOADING: "LOGINLOADING",
    USERLOGINRESPONSE: "USERLOGINRESPONSE",
    USERLOGINDATA: "USERLOGINDATA",
    USERLOGINERROR: "USERLOGINERROR",
    LOGINRESET: "LOGINRESET",
    SIGNUPLOADING: "SIGNUPLOADING",
    USERSIGNUPRESPONSE: "USERSIGNUPRESPONSE",
    USERSIGNUPDATA: "USERSIGNUPDATA",
    USERSIGNUPERROR: "USERSIGNUPERROR",
    SIGNUPRESET: "SIGNUPRESET",
}

export default actionTypes;